version: '3.8'
services:
  users-service:
    image: post-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/post-service
      - CONFIG_SERVER_URL=http://172.17.0.1:8888
      - DISCOVERY_SERVER_URL=http://172.17.0.1:8761/eureka/
    depends_on:
      - postgres
    networks:
      - my-network
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=users-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  pgdata: