services:
  post-service:
    container_name: papp
    image: post-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ppost:5432/post-service
      - CONFIG_SERVER_URL=http://172.17.0.1:8888
    depends_on:
      - postgres
    networks:
      - my-network
  postgres:
    container_name: ppost
    image: postgres:15
    environment:
      - POSTGRES_DB=post-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata_temp:/var/lib/postgresql/data
    networks:
      - my-network
networks:
  my-network:
    external: true
volumes:
  pgdata_temp:
