server:
  port: 8002
spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users-service
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
gateway:
  user-path: /gateway/users/